name: Deploy Frontend

on: 
  workflow_dispatch:
  schedule:
    - cron: "35 22 * * 1-6"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd Frontend
          npm ci

      - name: Build
        run: |
          cd Frontend
          VITE_API_URL=${{ secrets.VITE_API_URL }} \
          VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }} \
          VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }} \
          VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }} \
          npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          overwrite: true
          source: "Frontend/dist/*"
          target: "/var/www/jwpfe"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: echo "${{ secrets.PASSWORD }}" | sudo -S systemctl reload nginx
